spring: 
  batch: 
    initialize-schema: always
    job:
      enabled: false
  mvc:
    view:  
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-201804d
    username: postgres
    password: postgres
    tomcat: 
      default-auto-commit: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: cas.niconico.acount@gmail.com
    password: bdwvytvlxdotmsg#a
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
  jmx:
    default-domain: ec-201804d #複数のアプリを１つのサーバ上で動かす際に必要な設定
server:
  servlet:
    context-path: /ec-201804d